### ISSUE TITLE
Replace loaders by tags

### ISSUE THREAD

**Issue by msmsny** [yahoojapan/ConfigCacheBundle#11]
In order to replace loaders, we need to describe `setLoader` on `Bundle::boot()`.
I want to make this configurable by tags.

``` yaml
# src/Acme/DemoBundle/Resources/config/services.yml
services:
    acme_demo.array_loader:
        class: Acme\DemoBundle\Loader\ArrayLoader

    acme_demo.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\YamlFileLoader
        calls:
            - [addLoader, [@acme_demo.array_loader]]
```

``` php
<?php

// src/Acme/DemoBundle/AcmeDemoBundle.php
namespace Acme\DemoBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AcmeDemoBundle extends Bundle
{
    public function boot()
    {
        $loader = $this->container->get('acme_demo.yaml_file_loader');
        $this->container->get('config.acme_demo.sample')
            ->setLoader($loader)
            ->create()
            ;
    }
}
```

to

``` yaml
# src/Acme/DemoBundle/Resources/config/services.yml
services:
    acme_demo.array_loader:
        class: Acme\DemoBundle\Loader\ArrayLoader

    acme_demo.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\YamlFileLoader
        calls:
            - [addLoader, [@acme_demo.array_loader]]
        tags:
            - { name: config.loader, service: config.acme_demo.sample }
```

``` php
<?php

// src/Acme/DemoBundle/AcmeDemoBundle.php
namespace Acme\DemoBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AcmeDemoBundle extends Bundle
{
    public function boot()
    {
        $this->container->get('config.acme_demo.sample')->create();
    }
}
```
