### ISSUE TITLE
Register ConfigCache service by services.yml

### ISSUE THREAD

**Issue by msmsny** [yahoojapan/ConfigCacheBundle#24]
Provide a simple registering approach by the following settings:

``` yml
# src/Acme/DemoBundle/Resources/config/services.yml
services:
    acme_demo.config_cache:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\ConfigCache
        tags:
            - { name: config_cache.register, resource: sample.yml }
```
